organizations:
  - from: opengauss
    to: opengauss
    route: gitcode-to-gitee
    repos:
      - opengauss/docs
    exclude_repos:
      - opengauss/og-agreements
      - opengauss/org-issue


gitcode_token: "****"
gitee_token: "****"
