organizations:
  - from: ascend
    to: ascend
    route: gitee-to-gitcode
    repos:
      - ascend/cann-community
      - ascend/infrastructure
      - ascend/cann-hccl
      - ascend/cann-ops-adv
      - ascend/cann-ops
      - ascend/triton-ascend
      - ascend/ascendc-api-adv
      - ascend/samples
      - ascend/tensorflow
      - ascend/metadef


gitcode_token: ""
gitee_token: ""

